# Generated by Django 4.2.7 on 2023-11-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
    ]
